apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-landing
  labels:
    app: consul-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-landing
  template:
    metadata:
      labels:
        app: consul-landing
    spec:
      containers:
      - name: consul-landing
        image: consul-landing
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: consul-landing
spec:
  selector:
    app: consul-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consul-landing
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - consul.djnd.si
    - consul.danesjenovdan.si
    secretName: consul-landing-tls
  rules:
  - host: consul.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: consul-landing
            port:
              number: 80
  - host: consul.danesjenovdan.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: consul-landing
            port:
              number: 80
