apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-landing
resources:
- frontend.yaml
images:
  - name: parlameter-landing
    newName: rg.fr-par.scw.cloud/djnd/parlameter-landing
    newTag: 'dce533c44ee3d839a4f13a04d3d979f7e61e8a80'
