apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul-landing
resources:
- frontend.yaml
images:
  - name: consul-landing
    newName: rg.fr-par.scw.cloud/djnd/consul-landing
    newTag: '56ceab463c0d6612719245e1b888656444ece009'
