apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: consul-landing
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: consul-landing
    newName: rg.fr-par.scw.cloud/djnd/consul-landing
    newTag: '89581f7b8c8f055f97d2693e8f7cfbad2be45eba'
